CREATE TABLE audit_logs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    actor_type  VARCHAR(255)                            NOT NULL,
    actor_id    BIGINT                                  NOT NULL,
    action      VARCHAR(255)                            NOT NULL,
    entity_type VARCHAR(255)                            NOT NULL,
    entity_id   BIGINT,
    diff_json   TEXT,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_id  BIGINT,
    name       VARCHAR(255)                            NOT NULL,
    slug       VARCHAR(255)                            NOT NULL,
    is_active  BOOLEAN                                 NOT NULL,
    sort_order INTEGER,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE courier_roles
(
    courier_user_id BIGINT NOT NULL,
    role_id         BIGINT NOT NULL
);

CREATE TABLE courier_users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    phone     VARCHAR(255)                            NOT NULL,
    is_active BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_courier_users PRIMARY KEY (id)
);

CREATE TABLE customer_links
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_external_id VARCHAR(255),
    trader_id            BIGINT,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    contact_hash         VARCHAR(255),
    CONSTRAINT pk_customer_links PRIMARY KEY (id)
);

CREATE TABLE delivery_assignments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id    BIGINT,
    courier_id  BIGINT,
    accepted_at TIMESTAMP WITHOUT TIME ZONE,
    status      VARCHAR(255),
    CONSTRAINT pk_delivery_assignments PRIMARY KEY (id)
);

CREATE TABLE inventory_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id    BIGINT,
    qty_on_hand   INTEGER,
    qty_reserved  INTEGER,
    warehouse_id  BIGINT,
    reorder_level INTEGER,
    version       BIGINT,
    CONSTRAINT pk_inventory_items PRIMARY KEY (id)
);

CREATE TABLE order_lines
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id   BIGINT,
    product_id BIGINT,
    qty        INTEGER,
    unit_price DECIMAL,
    line_total DECIMAL,
    CONSTRAINT pk_order_lines PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number     VARCHAR(255),
    trader_id        BIGINT,
    status           VARCHAR(255),
    delivery_address VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    totals           DECIMAL,
    customer_link_id BIGINT,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE package_artifacts
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    trader_id          BIGINT                                  NOT NULL,
    artifact_file_path VARCHAR(255)                            NOT NULL,
    build_status       VARCHAR(255)                            NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_package_artifacts PRIMARY KEY (id)
);

CREATE TABLE product_images
(
    product_id BIGINT NOT NULL,
    image_url  VARCHAR(255)
);

CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku         VARCHAR(255),
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    base_price  DECIMAL                                 NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    category_id BIGINT,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE trader_allowed_categories
(
    trader_id   BIGINT NOT NULL,
    category_id BIGINT
);

CREATE TABLE trader_users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    trader_id     BIGINT                                  NOT NULL,
    role_id       BIGINT                                  NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    last_login_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_trader_users PRIMARY KEY (id)
);

CREATE TABLE traders
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    legal_name           VARCHAR(255)                            NOT NULL,
    display_name         VARCHAR(255)                            NOT NULL,
    domain               VARCHAR(255),
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    theme_config_json    TEXT,
    status               VARCHAR(255),
    ssl_cert_path        VARCHAR(255),
    ssl_key_db_encrypted VARCHAR(255),
    CONSTRAINT pk_traders PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    full_name  VARCHAR(255)                            NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    api_key    VARCHAR(255),
    active     BOOLEAN DEFAULT TRUE                    NOT NULL,
    approved   BOOLEAN DEFAULT FALSE                   NOT NULL,
    rejected   BOOLEAN DEFAULT FALSE                   NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_slug UNIQUE (slug);

ALTER TABLE trader_users
    ADD CONSTRAINT uc_e71a1e30222d51be3d2ac3b24 UNIQUE (trader_id, email);

ALTER TABLE orders
    ADD CONSTRAINT uc_orders_order_number UNIQUE (order_number);

ALTER TABLE products
    ADD CONSTRAINT uc_products_sku UNIQUE (sku);

ALTER TABLE traders
    ADD CONSTRAINT uc_traders_domain UNIQUE (domain);

ALTER TABLE users
    ADD CONSTRAINT uc_users_apikey UNIQUE (api_key);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE categories
    ADD CONSTRAINT FK_CATEGORIES_ON_PARENT FOREIGN KEY (parent_id) REFERENCES categories (id);

ALTER TABLE customer_links
    ADD CONSTRAINT FK_CUSTOMER_LINKS_ON_TRADER FOREIGN KEY (trader_id) REFERENCES traders (id);

ALTER TABLE delivery_assignments
    ADD CONSTRAINT FK_DELIVERY_ASSIGNMENTS_ON_COURIER FOREIGN KEY (courier_id) REFERENCES courier_users (id);

ALTER TABLE delivery_assignments
    ADD CONSTRAINT FK_DELIVERY_ASSIGNMENTS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE inventory_items
    ADD CONSTRAINT FK_INVENTORY_ITEMS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_CUSTOMER_LINK FOREIGN KEY (customer_link_id) REFERENCES customer_links (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_TRADER FOREIGN KEY (trader_id) REFERENCES traders (id);

ALTER TABLE order_lines
    ADD CONSTRAINT FK_ORDER_LINES_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_lines
    ADD CONSTRAINT FK_ORDER_LINES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE trader_users
    ADD CONSTRAINT FK_TRADER_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE trader_users
    ADD CONSTRAINT FK_TRADER_USERS_ON_TRADER FOREIGN KEY (trader_id) REFERENCES traders (id);

ALTER TABLE courier_roles
    ADD CONSTRAINT fk_courol_on_courier_user FOREIGN KEY (courier_user_id) REFERENCES courier_users (id);

ALTER TABLE courier_roles
    ADD CONSTRAINT fk_courol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE product_images
    ADD CONSTRAINT fk_product_images_on_product FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE trader_allowed_categories
    ADD CONSTRAINT fk_trader_allowed_categories_on_trader FOREIGN KEY (trader_id) REFERENCES traders (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user_entity FOREIGN KEY (user_id) REFERENCES users (id);